resources:
- name: source
  type: git
  check_every: 24h
  source:
    uri: https://github.com/jonm/s3pypi-gen-proj-index.git
    branch: master

- name: artifacts
  type: s3
  source:
    bucket: ((dest-s3-bucket))
    regexp: s3pypi-gen-proj-index/s3pypi-gen-proj-index-(.*).zip
    access_key_id: ((aws-access-key-id))
    secret_access_key: ((aws-secret-access-key))
    
jobs:
- name: build
  plan:
    - get: source
      trigger: true
    - task: make
      file: source/ci/task_make.yml
    - put: artifacts
      params:
        file: dist/s3pypi-gen-proj-index-*.zip
